// HELIX-PRESSURE-INDEX-RALPH-001.
//
// P02: the hosting mechanism serves the Index publicly. The route rides the
//      same whitelisted-page seam as /cortex; no generic file server.
// P11: the two surfaces render FROM THE STORE (generated by
//      helix-core tooling/scripts/exportPressureIndex.ts), server-rendered and
//      marked up for citation, with a PERMANENT per-entry address that resolves.
//
// The provenance assertions here are CONV-PI-1, which the plan requires to be
// asserted on the RENDERED output rather than the store: every published entry
// carries a source id, a source URL, a retrieval date and the publisher's own
// name for the record.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

process.env.DATA_DIR = process.env.DATA_DIR || await mkdtemp(join(tmpdir(), 'helix-test-'));
process.env.GEMINI_API_KEY = '';
const { server } = await import('../server.mjs');

const HOST = { Host: 'waitlist.helix.work' };

async function withServer(fn) {
  await new Promise((r) => server.listen(0, r));
  try {
    await fn(server.address().port);
  } finally {
    await new Promise((r) => server.close(r));
  }
}

test('GET /pressure-index serves the front page on any host, no session', async () => {
  await withServer(async (port) => {
    const res = await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST });
    assert.equal(res.status, 200);
    const body = await res.text();
    assert.match(body, /Pressure Index/);
    assert.match(body, /Issue 01/);
    assert.match(body, /28 August 2026/);
  });
});

/** The addresses issue 01 published under the positional scheme (P22 follow-up). */
const ALIAS_ID = /^PI-2026-(C|E|H|CQC)-\d{3}$/;

test('the front page renders entries FROM THE STORE, each with its source and retrieval date', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    // A real entry reference, a real official source, and a retrieval date.
    // The address scheme is now DERIVED from the publisher's own reference
    // (P22/P30 follow-up): the old `PI-2026-E-002` positional ids churned when
    // the feed reshuffled, so an entry reference is a source prefix and a
    // digest. The fifteen positional addresses still resolve, as aliases.
    assert.match(body, /PI-[A-Z]+-[0-9a-f]{10}/, 'no entry reference on the front page');
    assert.match(body, /https:\/\/www\.gov\.uk\//, 'no official source link on the front page');
    assert.match(body, /retrieved <time datetime="20\d\d-/, 'no machine-readable retrieval date');
    // The counts the issue states on its face, not a hand-typed number.
    assert.match(body, /<span>entries this issue<\/span>/);
    assert.match(body, /<span>official sources?<\/span>/);
    // The method block and the forward calendar.
    assert.match(body, /How this is built/);
    assert.match(body, /What lands next/);
  });
});

test('the sector filter serves a filtered page, and refuses an unknown sector', async () => {
  await withServer(async (port) => {
    const housing = await fetch(`http://127.0.0.1:${port}/pressure-index?sector=housing`, { headers: HOST });
    assert.equal(housing.status, 200);
    const body = await housing.text();
    assert.match(body, /Housing entries/);
    assert.match(body, /rel="canonical" href="https:\/\/helix\.work\/pressure-index\?sector=housing"/);

    const bogus = await fetch(`http://127.0.0.1:${port}/pressure-index?sector=retail`, { headers: HOST });
    assert.equal(bogus.status, 404, 'an unknown sector must not silently serve the whole register');
  });
});

test('a PERMANENT per-entry address resolves, and carries CONV-PI-1 in full', async () => {
  // Read the exported entries rather than naming one: the test must hold for
  // whatever the store published, not for a fixture somebody typed here.
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const all = (await readdir(dir)).filter((f) => f.endsWith('.html')).map((f) => f.replace(/\.html$/, ''));
  // The fifteen addresses issue 01 published under the positional scheme are
  // served as ALIAS pages: they resolve, and they say where the record lives
  // now. They are asserted separately, below, because they are deliberately
  // not entry pages.
  const ids = all.filter((id) => !ALIAS_ID.test(id));
  assert.ok(ids.length > 0, 'no entry pages were exported');

  await withServer(async (port) => {
    for (const id of ids) {
      const res = await fetch(`http://127.0.0.1:${port}/pressure-index/${id}`, { headers: HOST });
      assert.equal(res.status, 200, `${id} did not resolve`);
      const body = await res.text();
      // CONV-PI-1, all four, on the rendered output.
      assert.match(body, /<dt>Source id<\/dt>/, `${id}: no source id`);
      assert.match(body, /open the source/, `${id}: no source URL`);
      assert.match(body, /<dt>Retrieved<\/dt>/, `${id}: no retrieval date`);
      assert.match(body, /class="q">[^<]+</, `${id}: no publisher's own name for the record`);
      // The permanent address, stated on the page and canonical in the head.
      assert.match(body, new RegExp(`rel="canonical" href="https://helix\\.work/pressure-index/${id}"`),
        `${id}: no canonical permanent address`);
      // Marked up for citation.
      assert.match(body, /application\/ld\+json/, `${id}: no JSON-LD`);
      assert.match(body, /"isBasedOn"/, `${id}: JSON-LD does not point at its source`);
    }
  });
});

test('an address that was never published 404s rather than being invented', async () => {
  await withServer(async (port) => {
    for (const bad of ['PI-2026-H-999', '..%2F..%2Fserver.mjs', 'not_an_id']) {
      const res = await fetch(`http://127.0.0.1:${port}/pressure-index/${bad}`, { headers: HOST });
      assert.equal(res.status, 404, `${bad} should not resolve`);
    }
  });
});

test('CONV-PI-2 on the rendered output: a named organisation carries no reading of it', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const files = (await readdir(dir)).filter((f) => f.endsWith('.html'));
  const pages = await Promise.all(files.map((f) => readFile(join(dir, f), 'utf8')));

  // Presence control: an absence assertion over a set that contains no named
  // organisation would prove nothing at all.
  const named = pages.filter((p) => /<dt>Organisation<\/dt>/.test(p));
  assert.ok(named.length > 0, 'no entry names an organisation, so the absence proves nothing');

  for (const page of named) {
    // THE ASSERTION THIS TEST IS NAMED FOR. The disclaimer below is a statement
    // ABOUT the constraint; this is the constraint: no reading of a named
    // organisation is rendered anywhere on the page.
    assert.doesNotMatch(page, /<h2>The reading<\/h2>/,
      'an entry naming an organisation renders OUR reading of them (CONV-PI-2)');
    assert.match(page, /carries no assessment of them and infers no consequence for them/,
      'an entry naming an organisation must state that it carries no assessment of them');
  }
});

test('the front page says what the list IS, and its dates run in the order it shows them', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    // W1. A register whose oldest records were first published in 2013 and 2015
    // is not `this week`, and the page no longer says it is.
    assert.doesNotMatch(body, />This week</, 'the register is headed `This week` over records years older');
    assert.doesNotMatch(body, /pressure from, this week/);
    assert.match(body, />In this issue</);
    // and it states the span it actually covers, computed from the entries.
    assert.match(body, /entries, dated <time datetime="/);
    // W2. The date each row shows is the date the register is ordered by.
    const shown = [...body.matchAll(/<article class="entry"[\s\S]*?<b><time datetime="([^"]+)"/g)]
      .map((m) => Date.parse(m[1]));
    assert.ok(shown.length > 1, 'no dated entries on the front page');
    assert.deepEqual(shown, [...shown].sort((a, b) => b - a),
      'the visible date column does not run in the order the register is sorted in');
    // and the two dates are labelled distinctly.
    assert.match(body, /<em class="lbl">published<\/em>/);
    // W4. The `scraped, estimated or inferred` figure is the register's own count.
    assert.match(body, /<b>0<\/b><span>scraped, estimated or inferred<\/span>/);
    // W13. A sentence after a full stop starts with a capital.
    assert.doesNotMatch(body, /capped\.<\/b> [a-z]/, 'a sentence starts lowercase after a full stop');
  });
});

test('an entry dates itself under a label that means what the field means', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const ids = (await readdir(dir)).filter((f) => f.endsWith('.html'))
    .map((f) => f.replace(/\.html$/, '')).filter((id) => !ALIAS_ID.test(id));
  await withServer(async (port) => {
    for (const id of ids) {
      const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index/${id}`, { headers: HOST })).text();
      // W3. The date rendered here is GOV.UK's `first_published_at`, so the
      // label says first published rather than an unqualified `published`.
      assert.match(body, /<dt>First published<\/dt>/, `${id}: the publication date carries an inaccurate label`);
      assert.doesNotMatch(body, /<dt>Source published<\/dt>/, `${id}: the old label survives`);
      assert.doesNotMatch(body, /capped\.<\/b> [a-z]/, `${id}: a sentence starts lowercase after a full stop`);
    }
  });
});

// P30: the remaining feeds. The page's own account of where its entries come
// from is a claim a reader can check, so it is asserted on the PUBLISHED FILES
// and not only in the renderer's unit tests.
test('the method block names the licences these sources actually record', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();

    // The sentence used to read `under the Open Government Licence v3.0` for
    // every source. P30 landed a publisher that states no re-use licence at
    // all, so that literal became false about the page it was printed on.
    assert.match(body, /Each source records its own licence/,
      'the method block no longer says where its licences come from');
    assert.match(body, /Open Government Licence v3\.0/,
      'the licences the sources do record are not named');
    assert.match(body, /No re-use licence stated by the publisher/,
      'a source that states no licence is not disclosed as such');
    assert.doesNotMatch(body, /regulator APIs, under the Open Government Licence v3\.0/,
      'the page still claims one licence covers every source');
  });
});

test('the method block does not claim registers are compared before the diff exists', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    assert.match(body, /snapshotted on every run/, 'the page no longer says snapshots are taken');
    assert.doesNotMatch(body, /snapshotted and compared/,
      'the page claims a comparison that does not happen until the diff engine lands');
  });
});

test('every published entry page names the source it came from (CONV-PI-1)', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const files = (await readdir(dir)).filter((f) => f.endsWith('.html'));
  assert.ok(files.length >= 42, `only ${files.length} permanent addresses published`);

  // Every one of the eight feeds is represented, so a feed that silently
  // stopped publishing is a red rather than a slightly shorter issue.
  const pages = await Promise.all(files.map((f) => readFile(join(dir, f), 'utf8')));
  for (const source of [
    'govuk-search', 'cqc-ratings', 'ofgem-publications', 'desnz-statistics',
    'find-a-tender', 'planning-data', 'housing-ombudsman', 'judiciary-pfd',
  ]) {
    assert.ok(pages.some((p) => p.includes(source)), `no published entry cites ${source}`);
  }
});

test('no published entry is addressed by its position in a fetch', async () => {
  // A permanent address that changes what it means is worse than one that
  // 404s, because nothing tells the reader. The feeds that publish a rolling
  // window derive their id from the record, so next week's shift cannot
  // overwrite a cited entry.
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const files = (await readdir(dir)).filter((f) => f.endsWith('.html'));
  const churnable = files.filter((f) => /^PI-(HOS|OFG|FTS|DESNZ|PLN|PFD)-/.test(f));
  assert.ok(churnable.length > 0, 'no rolling-window entries published, so this proves nothing');
  for (const f of churnable) {
    assert.doesNotMatch(f, /-\d{3}\.html$/, `${f} is addressed by a position, not by its record`);
  }
});

// P22 follow-up: the fifteen addresses issue 01 published under the positional
// id scheme. They are live and citable, so they may not 404 and they may not
// quietly point at a different record.
test('every address published under the old scheme still resolves, and says what happened', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const aliases = (await readdir(dir)).filter((f) => f.endsWith('.html'))
    .map((f) => f.replace(/\.html$/, '')).filter((id) => ALIAS_ID.test(id));
  assert.equal(aliases.length, 15, 'the fifteen issue-01 addresses are not all being served');

  await withServer(async (port) => {
    for (const id of aliases) {
      const res = await fetch(`http://127.0.0.1:${port}/pressure-index/${id}`, { headers: HOST });
      assert.equal(res.status, 200, `${id} no longer resolves, and it is a published address`);
      const body = await res.text();
      // It names itself, so a reader who cited it knows they are in the right place.
      assert.match(body, new RegExp(id), `${id}: the page does not name the address that was cited`);
      // It points at the entry rather than pretending to BE it.
      assert.match(body, /rel="canonical" href="https:\/\/helix\.work\/pressure-index\/PI-[A-Z]+-[0-9a-f]{10}"/,
        `${id}: the canonical does not point at a permanent address`);
      assert.match(body, /noindex/, `${id}: a crawler could index this in place of the entry`);
      // And it explains, rather than silently swapping the reader's address.
      assert.match(body, /permanent address/, `${id}: no account of why the address moved`);
    }
  });
});

// P41 / MG-REQ-016: we publish our own misses.
test('the issue publishes whether its own feeds ran', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    assert.match(body, /Whether this issue&#39;s feeds ran|Whether this issue's feeds ran/,
      'the issue makes no statement about its own cadence');
    // Derived from the rows, so it names real feeds rather than a round number.
    assert.match(body, /of 8 feeds ran on their last expected schedule/,
      'the cadence claim is not counted from the registry rows');
  });
});

// P22: the page's account of the comparison is derived from the comparisons.
test('the method block reports the comparison that actually ran', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    assert.doesNotMatch(body, /The first comparison publishes once two snapshots a week apart exist/,
      'the page still promises a comparison that has now happened');
    assert.match(body, /registers? had been read twice/, 'the page does not say what it compared');
    // THE READING CARRIES ITS OWN INSTANT, and that is what makes it stay true.
    // The store moves on every end-to-end run: the page said `the widest gap
    // being 9 hours` while the store said 12, because a verification run had
    // widened it. A figure derived at export and phrased as a claim about NOW
    // is true when it is written and false an hour later, on the one page whose
    // whole pitch is that nothing on it is asserted.
    assert.match(body, /Reading the store as at \d{2}:\d{2} on \d{1,2} \w+ \d{4}/,
      'the comparison does not say when it was read, so a later run can contradict it');
    assert.doesNotMatch(body, /registers? have been read twice/,
      'the comparison still speaks in the present tense about a reading it took once');
  });
});
