// HELIX-PRESSURE-INDEX-RALPH-001.
//
// P02: the hosting mechanism serves the Index publicly. The route rides the
//      same whitelisted-page seam as /cortex; no generic file server.
// P11: the two surfaces render FROM THE STORE (generated by
//      helix-core tooling/scripts/exportPressureIndex.ts), server-rendered and
//      marked up for citation, with a PERMANENT per-entry address that resolves.
//
// The provenance assertions here are CONV-PI-1, which the plan requires to be
// asserted on the RENDERED output rather than the store: every published entry
// carries a source id, a source URL, a retrieval date and the publisher's own
// name for the record.
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

process.env.DATA_DIR = process.env.DATA_DIR || await mkdtemp(join(tmpdir(), 'helix-test-'));
process.env.GEMINI_API_KEY = '';
const { server } = await import('../server.mjs');

const HOST = { Host: 'waitlist.helix.work' };

async function withServer(fn) {
  await new Promise((r) => server.listen(0, r));
  try {
    await fn(server.address().port);
  } finally {
    await new Promise((r) => server.close(r));
  }
}

test('GET /pressure-index serves the front page on any host, no session', async () => {
  await withServer(async (port) => {
    const res = await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST });
    assert.equal(res.status, 200);
    const body = await res.text();
    assert.match(body, /Pressure Index/);
    assert.match(body, /Issue 01/);
    assert.match(body, /28 August 2026/);
  });
});

test('the front page renders entries FROM THE STORE, each with its source and retrieval date', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    // A real entry reference, a real official source, and a retrieval date.
    assert.match(body, /PI-2026-[EHCX]-\d{3}/, 'no entry reference on the front page');
    assert.match(body, /https:\/\/www\.gov\.uk\//, 'no official source link on the front page');
    assert.match(body, /retrieved <time datetime="20\d\d-/, 'no machine-readable retrieval date');
    // The counts the issue states on its face, not a hand-typed number.
    assert.match(body, /<span>entries this issue<\/span>/);
    assert.match(body, /<span>official sources?<\/span>/);
    // The method block and the forward calendar.
    assert.match(body, /How this is built/);
    assert.match(body, /What lands next/);
  });
});

test('the sector filter serves a filtered page, and refuses an unknown sector', async () => {
  await withServer(async (port) => {
    const housing = await fetch(`http://127.0.0.1:${port}/pressure-index?sector=housing`, { headers: HOST });
    assert.equal(housing.status, 200);
    const body = await housing.text();
    assert.match(body, /Housing entries/);
    assert.match(body, /rel="canonical" href="https:\/\/helix\.work\/pressure-index\?sector=housing"/);

    const bogus = await fetch(`http://127.0.0.1:${port}/pressure-index?sector=retail`, { headers: HOST });
    assert.equal(bogus.status, 404, 'an unknown sector must not silently serve the whole register');
  });
});

test('a PERMANENT per-entry address resolves, and carries CONV-PI-1 in full', async () => {
  // Read the exported entries rather than naming one: the test must hold for
  // whatever the store published, not for a fixture somebody typed here.
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const ids = (await readdir(dir)).filter((f) => f.endsWith('.html')).map((f) => f.replace(/\.html$/, ''));
  assert.ok(ids.length > 0, 'no entry pages were exported');

  await withServer(async (port) => {
    for (const id of ids) {
      const res = await fetch(`http://127.0.0.1:${port}/pressure-index/${id}`, { headers: HOST });
      assert.equal(res.status, 200, `${id} did not resolve`);
      const body = await res.text();
      // CONV-PI-1, all four, on the rendered output.
      assert.match(body, /<dt>Source id<\/dt>/, `${id}: no source id`);
      assert.match(body, /open the source/, `${id}: no source URL`);
      assert.match(body, /<dt>Retrieved<\/dt>/, `${id}: no retrieval date`);
      assert.match(body, /class="q">[^<]+</, `${id}: no publisher's own name for the record`);
      // The permanent address, stated on the page and canonical in the head.
      assert.match(body, new RegExp(`rel="canonical" href="https://helix\\.work/pressure-index/${id}"`),
        `${id}: no canonical permanent address`);
      // Marked up for citation.
      assert.match(body, /application\/ld\+json/, `${id}: no JSON-LD`);
      assert.match(body, /"isBasedOn"/, `${id}: JSON-LD does not point at its source`);
    }
  });
});

test('an address that was never published 404s rather than being invented', async () => {
  await withServer(async (port) => {
    for (const bad of ['PI-2026-H-999', '..%2F..%2Fserver.mjs', 'not_an_id']) {
      const res = await fetch(`http://127.0.0.1:${port}/pressure-index/${bad}`, { headers: HOST });
      assert.equal(res.status, 404, `${bad} should not resolve`);
    }
  });
});

test('CONV-PI-2 on the rendered output: a named organisation carries no reading of it', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const files = (await readdir(dir)).filter((f) => f.endsWith('.html'));
  const pages = await Promise.all(files.map((f) => readFile(join(dir, f), 'utf8')));

  // Presence control: an absence assertion over a set that contains no named
  // organisation would prove nothing at all.
  const named = pages.filter((p) => /<dt>Organisation<\/dt>/.test(p));
  assert.ok(named.length > 0, 'no entry names an organisation, so the absence proves nothing');

  for (const page of named) {
    // THE ASSERTION THIS TEST IS NAMED FOR. The disclaimer below is a statement
    // ABOUT the constraint; this is the constraint: no reading of a named
    // organisation is rendered anywhere on the page.
    assert.doesNotMatch(page, /<h2>The reading<\/h2>/,
      'an entry naming an organisation renders OUR reading of them (CONV-PI-2)');
    assert.match(page, /carries no assessment of them and infers no consequence for them/,
      'an entry naming an organisation must state that it carries no assessment of them');
  }
});

test('the front page says what the list IS, and its dates run in the order it shows them', async () => {
  await withServer(async (port) => {
    const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index`, { headers: HOST })).text();
    // W1. A register whose oldest records were first published in 2013 and 2015
    // is not `this week`, and the page no longer says it is.
    assert.doesNotMatch(body, />This week</, 'the register is headed `This week` over records years older');
    assert.doesNotMatch(body, /pressure from, this week/);
    assert.match(body, />In this issue</);
    // and it states the span it actually covers, computed from the entries.
    assert.match(body, /entries, dated <time datetime="/);
    // W2. The date each row shows is the date the register is ordered by.
    const shown = [...body.matchAll(/<article class="entry"[\s\S]*?<b><time datetime="([^"]+)"/g)]
      .map((m) => Date.parse(m[1]));
    assert.ok(shown.length > 1, 'no dated entries on the front page');
    assert.deepEqual(shown, [...shown].sort((a, b) => b - a),
      'the visible date column does not run in the order the register is sorted in');
    // and the two dates are labelled distinctly.
    assert.match(body, /<em class="lbl">published<\/em>/);
    // W4. The `scraped, estimated or inferred` figure is the register's own count.
    assert.match(body, /<b>0<\/b><span>scraped, estimated or inferred<\/span>/);
    // W13. A sentence after a full stop starts with a capital.
    assert.doesNotMatch(body, /capped\.<\/b> [a-z]/, 'a sentence starts lowercase after a full stop');
  });
});

test('an entry dates itself under a label that means what the field means', async () => {
  const dir = join(import.meta.dirname, '..', 'public', 'pressure-index');
  const ids = (await readdir(dir)).filter((f) => f.endsWith('.html')).map((f) => f.replace(/\.html$/, ''));
  await withServer(async (port) => {
    for (const id of ids) {
      const body = await (await fetch(`http://127.0.0.1:${port}/pressure-index/${id}`, { headers: HOST })).text();
      // W3. The date rendered here is GOV.UK's `first_published_at`, so the
      // label says first published rather than an unqualified `published`.
      assert.match(body, /<dt>First published<\/dt>/, `${id}: the publication date carries an inaccurate label`);
      assert.doesNotMatch(body, /<dt>Source published<\/dt>/, `${id}: the old label survives`);
      assert.doesNotMatch(body, /capped\.<\/b> [a-z]/, `${id}: a sentence starts lowercase after a full stop`);
    }
  });
});
